Grace-Shopper-Jalapenos/Grace-Shopper-App

.travis.yml
README.md
server/db/Index.js
server/server.js
test/spec.js

feat: Test travis

---

.travis.yml
package.json
server/db/db.js
test/spec.js

Feature: Travis officially works

---

client/actionCreators/shoppingCart.js
client/components/AllProducts.jsx
client/components/App.jsx
client/components/Cart.jsx
client/reducers/cartReducer.js
client/store/store.js
public/assets/style.css
server/api/orders.js
server/db/Index 2.js
server/db/db 2.js

Add to cart added, not completed

added cart feature

---

client/actionCreators/allProducts.js
client/actionCreators/allUsers.js
client/actionCreators/singleUser.js
client/components/App.jsx
client/components/Forms/SignUp/SignUp.jsx
client/components/Forms/SignUp/resetSignUpFormStyles.js
client/components/Forms/SignUp/signUpValidator.js
client/components/Forms/index.js
client/components/SignUp.jsx
client/reducers/allUsersReducer.js
client/reducers/singleProductReducer.js
client/reducers/singleUserReducer.js
client/store/store.js
package-lock.json
package.json
public/assets/signup.css
server/api/users.js
server/db/model/Users.js
server/db/seed.js
server/server.js
test/product.spec.js

Added some features including: 
- Sign up functionally adds a user through a POST route to the api
- Nice UI for the sign up page
- Added redux logger
- Added new actions and reducers for User types

FEATURE: Sign up adds new user

---

.env
client/components/Forms/SignIn/SignIn.jsx
client/components/Forms/SignIn/signInValidator.js
client/components/Forms/SignUp/SignUp.jsx
client/store/actionCreators/singleUser.js
client/store/reducers/signInReducer.js
client/store/store.js
package-lock.json
package.json
server/api/auth.js
server/db/model/Users.js
server/server.js

Changes include:
- Passwords are hashed
- Created "/api/auth" to handle authorization requests
- Updates Users model to handle authentication and JWT
- Installed jsonwebtoken and bcrypt
- Fleshed out the SignIn component
- Stores token in local storage
Not Completed: 
- No user feedback on sign in, you must see it through the react store or in a logger
- no logout button, but the function is there in redux in the "singleUser" action folder
- Sign Up is not functional yet

FEATURE: Signing In Implemented

---

client/components/App.jsx
client/components/Forms/SignIn/SignIn.jsx
client/components/Forms/SignUp/SignUp.jsx
client/components/Header.jsx
client/store/actionCreators/singleUser.js
client/store/reducers/signInReducer.js
public/assets/signin.css
public/assets/signup.css

- Reactive signin/signup components tell you if you are already signed in
- Sign in and Sign up both now work
- On app mount, it searches for a localStorage JWI token to attempt a login. This enables users to refresh and stay logged in.
- Signing in affects the header! Adds a link to individual profile
- Logout now implemented only if a user is signed in

FEATURE: New Sign-In Features

---

server/app.js
server/server.js
test/product.spec.js

I just separated init from app 
when together it kept calling syncandseed every export of app when they were on same file

feat: travis done

---

client/components/App.jsx
client/components/Forms/SignIn/SignIn.jsx
client/components/Forms/SignIn/signInValidator.js
client/components/Forms/SignUp/SignUp.jsx
client/components/Forms/SignUp/signUpValidator.js
client/components/Forms/authenticate.js
client/store/actionCreators/allUsers.js
client/store/reducers/allUsersReducer.js
server/api/auth.js
server/api/users.js
server/db/model/Users.js
server/server.js

Features:
- Error shows for invalid credentials on sign in
- Error shows if email and/or username are already taken (CURRENT BUG HERE, shows both every time)
- Database now mandates that emails and usernames be unique
- Added error-handling endware to our server
- User POST route handles duplicate value error
- /api/auth GET route will return a 401 error if supplied directly with an invalid token

Features: Sign In / Up error handling with Routes

---

client/components/SingleProduct.jsx
server/api/products.js
server/db/seed.js

I changed the db again cause when I wanted to add foreign keys to my reviews to test out my component
It kept saying they didnt exist even though i saw them in the DB weird right?
After i changed it, everything worked 🤷‍♂️
Also displayed reviews on single component didnt use any review routes just added Reviews model in single product api route
Not sure if thats cool or lazy coding let me know and i can change it  👍

feat: reviews on display

---

client/components/AllProducts.jsx
client/components/App.jsx
client/store/reducers/cartReducer.js
public/assets/style.css

Hi guys, I updated the cart to track our total as more things are added to the cart. Also, did  some basic flexbox for our store page.

updates to cart total and css

---

client/components/EditProduct.jsx
client/components/SingleProduct.jsx

Edit Product Form is complete. You will see an edit button above a single product. However, I need to create a back-end route to update the db with our edits.

created edit product form

---

server/api/categories.js
server/api/errors/badSyntax.js
server/api/errors/conflict.js
server/api/errors/index.js
server/api/errors/notFound.js
server/api/orders.js
server/api/products.js
server/api/reviews.js
server/api/users.js
server/app.js
server/db/model/Orders.js
server/db/model/ProductsOrders.js
server/db/model/Reviews.js
server/db/model/Users.js
server/db/model/index.js

**Routes**
- Users: GET, POST, PUT, DELETE
- Reviews: GET, POST, PUT, DELETE
- Products: GET, POST, PUT, DELETE,
- Orders: GET, POST, DELETE
- Categories: to-do
- Enhanced error handling for server
**Database**
- Modified Association between Products and Orders to M:M
- Created new model: ProductsOrders

FEATURE: More backend routes

---

server/api/categories.js
server/api/orders.js
server/api/products.js
server/api/reviews.js
server/api/users.js

Some problems with asynchronous database calls have been fixed, particularly with our delete routes.

Back End Bug Squashing

---

client/components/EditProduct.jsx
client/store/actionCreators/singleProduct.js
server/api/products.js

Just doing a push and pull to avoid back-end conflict.

editForm updates

---

client/components/EditProduct.jsx
server/api/products.js

You will see a button on the top of the SingleProduct page that you can click to edit the details. On submit this will also update the database. However, the page is not re-rendering right now. I need to look into that.

Product Edit Form Mostly Working

---

client/components/App.jsx
client/components/EditProduct.jsx
client/components/SingleProduct.jsx
client/store/actionCreators/singleProduct.js
client/store/reducers/allProductsReducer.js
client/store/reducers/singleProductReducer.js
server/api/products.js

Edit component is now working.

edit component works now

---

package.json
server/db/db.js
server/db/model/Categories.js
server/db/seed.js
test/product.spec.js

Tests are now tested with actual data lol
had to extend timeout of mocha because the Met API is what slows it down 
we should ask elliot on saturday if normal or better way

feat: added more tests will it make travis slow

---

client/components/App.jsx
client/components/Forms/SignIn/SignIn.jsx
client/components/SingleUser.jsx
server/db/model/ProductsOrders.js
server/db/seed.js

Added a single user component but it is the bare minimum, gonna flesh it out today.
Also added seed data for our new many-to-many structure. I wanted to do a pull request early so we didn't have any merge conflicts

Single User Component

---

client/components/App.jsx
client/components/Forms/SignIn/SignIn.jsx
client/components/Forms/SignUp/SignUp.jsx
client/components/Header.jsx
client/components/SingleUser.jsx
client/components/Users/Account.jsx
client/components/Users/AccountForm.jsx
client/components/Users/Orders.jsx
client/components/Users/SingleUser.jsx
public/assets/header.css
public/assets/style.css
public/assets/user.css
server/api/orders.js
server/db/model/ProductsOrders.js
server/db/seed.js

check it out by going to /api/orders or /api/orders/:id

API Feature: Orders API now includes prices attached to each item in the order

---

client/components/Users/Account.jsx
client/components/Users/AdminScreen.jsx
client/components/Users/Orders.jsx
client/components/Users/SingleUser.jsx
package-lock.json
package.json
public/assets/profile.css
public/assets/user.css

- can view account info, orders, and admin if you are an admin.
- TODO: right now, any user can go to /user/:id/admin and see the page. we will limit that in the future by asking for credentials somehow.

FEATURE: User account now displays

---

client/components/Review/FormReview.jsx
client/components/Review/ReviewsProduct.jsx
client/components/SingleProduct.jsx
client/store/actionCreators/reviews.js
client/store/reducers/reviewReducer.js
server/api/reviews.js
server/db/seed.js
test/product.spec.js

Able to post review and new review displays on screen but i gotta look into how it appears when user is signed in or not 
For now it has one particular user so it can work 
Might have to rearrange things

feat: added form for review

---

client/components/AllProducts.jsx
client/store/actionCreators/shoppingCart.js
package-lock.json
server/api/orders.js
server/db/model/ProductsOrders.js
server/db/seed.js

made updates to cart needs fixing tho

---

client/components/Users/Account.jsx
client/components/Users/Dialogues/EditUserAccount.jsx
client/components/Users/OrderItem.jsx
client/components/Users/Orders.jsx
client/store/actionCreators/singleUser.js
client/store/reducers/allProductsReducer.js
client/store/reducers/allUsersReducer.js
client/store/reducers/signInReducer.js
public/assets/user.css
server/api/users.js
server/db/model/Users.js
server/db/seed.js

You can view your personal information, as well as edit it and log out from this screen:
/api/user/:id/account

Feature: User Account Page

---

client/components/AllProducts.jsx
client/store/actionCreators/shoppingCart.js
client/store/reducers/cartReducer.js
server/api/cart.js
server/api/orders.js
server/db/model/Cart.js

Cart model now exists and has quantity

cart now has quantity

---

client/components/AllProducts.jsx
package-lock.json

Fixed bug where only signed-in users could add to cart. Not both the guest and the signed-in user can add to cart.

cart can be used by guest

---

client/components/AllProducts.jsx
client/store/actionCreators/shoppingCart.js
client/store/reducers/cartReducer.js
server/api/cart.js
server/db/model/Cart.js
server/db/model/Products.js

Still working on getting the cart displayed correctly.

Still updating cart

---

client/components/AllProducts.jsx
client/store/reducers/cartReducer.js
server/db/db 2.js

Managed to fix the cart. Now the Cart table in the database updates correctly and the cart displays the information correctly on the store page. This will also persist as it's coming from the database directly

Cart is now working

---

client/components/Users/OrderItem.jsx
client/components/Users/SingleUser.jsx
public/assets/user.css

- displays all previous orders, including date purchased, total price, name with a link to the product, and artist name (eventually)

Feature: A basic order page for users

---

client/components/AllProducts.jsx
client/components/App.jsx
client/components/Review/SingleReview.jsx
client/components/SearchBar.jsx
client/store/actionCreators/reviews.js
server/api/products.js
server/db/seed.js

AllProducts is not in App but SearchBar replaced it but i have the AllProducts in the search component so they both display 
that way it filters out the display when typing in the search bar

feat: search bar done had to move some AllProducts under search bar component

---

client/components/AllProducts.jsx
client/store/actionCreators/shoppingCart.js
client/store/reducers/cartReducer.js
server/api/cart.js
server/db/db.js

can now delete from cart

---

client/components/AllProducts.jsx
client/store/actionCreators/shoppingCart.js
client/store/reducers/cartReducer.js
server/api/cart.js

Can now increase the quantity of an item in cart.

can now increase quantity of items in cart

---

client/components/AllProducts.jsx
client/store/actionCreators/shoppingCart.js
client/store/reducers/cartReducer.js
package-lock.json
server/api/cart.js

A user can now decrease the quantity of an item in cart.

Can not decrease quantity in cart

---

babel.config.json
client/components/AllProducts.jsx
client/components/Cart.jsx
client/components/CheckoutWithStripe.jsx
client/store/actionCreators/shoppingCart.js
package-lock.json
package.json
server/api/stripeCheckout.js

Stripe button added to Cart page. Still needs some bug fixing.

added strip functionality

---

client/components/AllProducts.jsx
client/components/App.jsx
package-lock.json

Proceed to checkout now routes a user based on their status.

Proceed to checkout button now redirects user

---

server/db/seed.js

feat: added categories

---

client/components/Admin/AdminArtists.jsx
client/components/Admin/AdminInventory.jsx
client/components/Admin/AdminUsers.jsx
client/components/Admin/dialogs/UserDialogue.jsx
client/components/Users/Account.jsx
client/store/actionCreators/allUsers.js
client/store/actionCreators/singleProduct.js
client/store/actionCreators/singleUser.js
client/store/reducers/allProductsReducer.js
client/store/reducers/artistsReducer.js
client/store/reducers/categoriesReducer.js
client/store/reducers/signInReducer.js
client/store/store.js
server/api/admins.js
server/api/auth.js

Feature: Admin can add users and products now

---

client/components/CheckoutWithStripe.jsx
package-lock.json
package.json
server/api/stripeCheckout.js
server/app.js

Stripe routes working, but still trying to fix some errors.

Still trying to get stripe to work

---

client/components/SingleProduct.jsx
server/db/Index 2.js
server/db/db 2.js
server/db/model/ProductsCategories.js
server/db/model/index.js
server/db/seed.js

Many to many for multiple categories

feat: added many to many for categories

---

client/components/CheckoutWithStripe.jsx
package-lock.json
package.json
server/api/stripeCheckout.js

Some more updates, but missing a required param. Will need to fix.

More updates to stripe still not working fully

---

client/components/CheckoutWithStripe.jsx
package-lock.json
server/api/stripeCheckout.js

Stripe checkout is now successful.

I kinda got stripe to work

---

client/components/AllProducts.jsx
client/components/Cart.jsx
client/components/CheckoutWithStripe.jsx
client/components/SingleProduct.jsx

I just updated the cart section so that now users cannot add more items to cart than what we have in stock. They can also no longer go below 0.

The + and - signs now work properly based on stock

---

package-lock.json
server/api/orders.js

I just updated the Orders route so that now upon checkout our stock in the database is correctly updated.

Stock in db now goes down upon checkout

---

client/components/Admin/AdminOrderItem.jsx
client/components/Admin/AdminOrders.jsx
client/components/Users/OrderItem.jsx
client/store/actionCreators/orders.js
client/store/reducers/allUsersReducer.js
client/store/reducers/singleUserReducer.js
public/assets/user.css
server/api/orders.js
server/db/model/Orders.js
server/db/seed.js

Adding more functionality for admin

Feature: Admin can delete user orders

---

client/components/AllProducts.jsx
client/components/Cart.jsx
client/components/SingleProduct.jsx
server/db/seed.js

updated for the guest Issue

---

client/components/Cart.jsx
package-lock.json
package.json
server/api/orders.js
server/api/stripeCheckout.js

updated the order route as discussed

updated order route

---

client/components/Cart.jsx
public/assets/style.css

Now you will see an order complete page.

Now shows purchases upon checkout
